// Generated by CoffeeScript 1.3.3
(function() {
  var IS_NODE, Table, properties, set, __root__, _ref;

  IS_NODE = typeof exports !== 'undefined';

  __root__ = typeof exports !== "undefined" && exports !== null ? exports : ((_ref = this.intermine) != null ? _ref : this.intermine = {});

  if (IS_NODE) {
    set = require('./util').set;
  } else {
    set = this.intermine.funcutils.set;
  }

  properties = ['attributes', 'references', 'collections'];

  Table = (function() {

    function Table(_arg) {
      var c, prop, refProp, _, _i, _j, _len, _len1, _ref1, _ref2;
      this.name = _arg.name, this.attributes = _arg.attributes, this.references = _arg.references, this.collections = _arg.collections;
      this.fields = {};
      this.superClasses = arguments[0]['extends'];
      for (_i = 0, _len = properties.length; _i < _len; _i++) {
        prop = properties[_i];
        (set(this[prop]))(this.fields);
      }
      _ref1 = properties.slice(1);
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        refProp = _ref1[_j];
        (set(this[refProp]))(this.fields);
      }
      _ref2 = this.collections;
      for (_ in _ref2) {
        c = _ref2[_];
        c.isCollection = true;
      }
    }

    Table.prototype.toString = function() {
      return "[Table name=" + this.name + "]";
    };

    return Table;

  })();

  exports.Table = Table;

}).call(this);
